# Generated by Django 3.1.6 on 2021-02-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom', models.CharField(blank=True, max_length=250, null=True)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('tel', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('date_ajout', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('nb_mouton_acheter', models.IntegerField(blank=True, default=0, null=True)),
                ('nb_mouton_vendu', models.IntegerField(blank=True, default=0, null=True)),
                ('prix_achat', models.IntegerField(blank=True, default=0, null=True)),
                ('date_achat', models.DateField()),
                ('lieux_achat', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=250, null=True)),
                ('etat', models.CharField(blank=True, default='En Stock', max_length=250, null=True)),
                ('couleur', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, default='media/photos/profile/profile_pic.png', upload_to='media/photos/profile')),
                ('categorie', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Achat.categorie')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Achat.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_vente', models.CharField(blank=True, max_length=250, null=True)),
                ('date_vente', models.DateField(auto_now_add=True, null=True)),
                ('nb_mouton_vendu', models.IntegerField(blank=True, default=1, null=True)),
                ('prix_vente_totale', models.IntegerField(blank=True, default=1, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Achat.client')),
                ('mouton', models.ManyToManyField(blank=True, to='Achat.Mouton')),
            ],
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(blank=True, default=0, null=True)),
                ('date_enc', models.DateField(auto_now_add=True, null=True)),
                ('etat_enc', models.CharField(blank=True, default='E', max_length=20, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Achat.client')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Achat.vente')),
            ],
        ),
    ]
