# Generated by Django 3.1.6 on 2021-02-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/mouton'),
        ),
    ]
