# Generated by Django 3.1.6 on 2021-02-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0003_auto_20210203_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='num_vente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
