# Generated by Django 3.1.6 on 2021-02-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0004_auto_20210203_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='mouton',
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_vente', models.IntegerField(blank=True, default=0, null=True)),
                ('mouton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Achat.mouton')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Achat.vente')),
            ],
            options={
                'unique_together': {('vente', 'mouton')},
            },
        ),
    ]
