# Generated by Django 3.1.6 on 2021-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0005_auto_20210203_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='nb_mouton_vendu',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='prix_vente_totale',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
