# Generated by Django 3.1.6 on 2021-02-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achat', '0006_auto_20210203_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=25, null=True)),
                ('rgb', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
